### ISSUE TITLE
No module named  'google'

### ISSUE THREAD

**Issue by AuthenticCamel** [gauravsacc/MMM-GoogleAssistant#1]
Hi,
I have been trying to use this module to integrate the google assistant into my MagicMirror. but when i try to run assistant.py I am greeted with 

```
Traceback (most recent call last):   
     File "assistant.py", line 24, in <module>
        import google.oauth2.credentials
ImportError: No module named 'google'
```

The google assistant running using the sample from google works fine with no issues
https://developers.google.com/assistant/sdk/prototype/getting-started-pi-python/run-sample

any suggestions?
Thanks

**Comment by christopherpthomas** [comment]
Same here!

**Comment by gauravsacc** [comment]
The python sample from the google docs creates a virtual python3 environment. Try running it via  following command
`/home/pi/env/bin/python3 -u assistant.py`

**Comment by AuthenticCamel** [comment]
Thanks
That seems to have solved that issue, but now a different module issue

```
pi@raspberrypi:~ $ /home/pi/env/bin/python3 -u assistant.py
Traceback (most recent call last):   
     File "assistant.py", line 30, in <module>
        import pubnub.callbacks import SubscribeCallback
ImportError: No module named 'pubnub'
```

any further thoughts ?
Thanks

**Comment by gauravsacc** [comment]
I should have added this to documentation but you need to install pubnub dependencies
`pip install 'pubnub>=4.0.13'`

**Comment by AuthenticCamel** [comment]
Thanks for your help, I've got it working.

pip wouldn't let me install pubnub>=4.0.13, doesn't seem to be available yet (https://pypi.python.org/simple/pubnub/ version 4.0.13 isn't there).
So I used 4.0.12 instead. I also had to enter the virtual python3 environment before installing. In the end I used:

```
$ python3 -m venv env
$ source env/bin/activate
(env) $ python -m pip install 'pubnub>=4.0.12'

$ /home/pi/env/bin/python3 -u assistant.py
```

So now it's all working,
Thanks again.

**Comment by gauravsacc** [comment]
Sweet!! 
Pubnub documentation says it should be available [https://www.pubnub.com/docs/python/pubnub-python-sdk]
I've updated the Readme to install pubnub dependencies.
Closing the issue
