### ISSUE TITLE
No module named 'pubnub'

### ISSUE THREAD

**Issue by mnail79** [gauravsacc/MMM-GoogleAssistant#10]
Hi.
After all steps from documentation, last command give me an error:
pi@mirror:~/env/bin $ /home/pi/env/bin/python3 -u /home/pi/assistant.py
Traceback (most recent call last):
  File "/home/pi/assistant.py", line 30, in <module>
    from pubnub.callbacks import SubscribeCallback
ImportError: No module named 'pubnub'

I have already read another issues and already do all recommendations, but still have the same error.

**Comment by mnail79** [comment]
Can somebody help me? I'm trying about 1 week, but nothing. I can give teamviewer or skype demonstration

**Comment by gauravsacc** [comment]
you sure you have pubnub installed correctly? Are you able to run a pubnub HelloWorld Sample without any errors https://www.pubnub.com/docs/python/pubnub-python-sdk

**Comment by mnail79** [comment]
No. I didnt it . But, I check python version. In env it is 3, and not in env it is 2.7. May be this is a problem?

**Comment by gauravsacc** [comment]
Yes please try running the python script in the python 3 virtual environment.

**Comment by mnail79** [comment]
Google assistant demo works fine on virtual environment. You mean assistant.py script, or pubnub demo script?

**Comment by gauravsacc** [comment]
You should be running assistant.py script in the virtual environment. Also, make sure to install pubnub dependencies in the virtual environment.

**Comment by mnail79** [comment]
Ok. I will try run assistant.py in the virtual environment. And if it will be ok, I must always run it from virtual environment?

**Comment by gauravsacc** [comment]
Yes

**Comment by mnail79** [comment]
pi@mirror:~ $ /home/pi/env/bin/python3 -u assistant.py
Traceback (most recent call last):
  File "assistant.py", line 30, in <module>
    from pubnub.callbacks import SubscribeCallback
ImportError: No module named 'pubnub'
pi@mirror:~ $ source env/bin/activate                                           (env) pi@mirror:~ $ google-assistant-demo
ON_MUTED_CHANGED:
  {u'is_muted': False}
ON_START_FINISHED
^C(env) pi@mirror:~ /home/pi/env/bin/python3 -u assistant.py
Traceback (most recent call last):
  File "assistant.py", line 30, in <module>
    from pubnub.callbacks import SubscribeCallback
ImportError: No module named 'pubnub'
(env) pi@mirror:~ $ python assistant.py
Traceback (most recent call last):
  File "assistant.py", line 30, in <module>
    from pubnub.callbacks import SubscribeCallback
ImportError: No module named pubnub.callbacks
(env) pi@mirror:~ $ python3 assistant.py
Traceback (most recent call last):
  File "assistant.py", line 30, in <module>
    from pubnub.callbacks import SubscribeCallback
ImportError: No module named 'pubnub'
(env) pi@mirror:~ $

**Comment by mnail79** [comment]
What is whong?

**Comment by mnail79** [comment]
(env) pi@mirror:~ $ sudo pip install 'pubnub >=4.0.13'
Requirement already satisfied: pubnub>=4.0.13 in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: pycryptodomex>=3.3 in /usr/local/lib/python2.7/dist-packages (from pubnub>=4.0.13)
Requirement already satisfied: requests>=2.4 in /usr/lib/python2.7/dist-packages (from pubnub>=4.0.13)
Requirement already satisfied: six>=1.10 in /usr/lib/python2.7/dist-packages (from pubnub>=4.0.13)
(env) pi@mirror:~ $

**Comment by mnail79** [comment]
WHat I have to do else to resolve my problem?

**Comment by Drogon1** [comment]
Hi, I have the same error.
Pubnub's module is correctly installed, also in env like mnail79. The demo script works (assistant and pubnub hello word)
Could you help us? Thanks

**Comment by gauravsacc** [comment]
Do you see pubnub folders in this directory /home/pi/env/lib/python3.5/site-packages

**Comment by mnail79** [comment]
No. I havent

**Comment by mnail79** [comment]
pi@mirror:~/env/lib/python3.5/site-packages/python/pubnub $ ls
builders.py       endpoints      models              pubnub_twisted.py
callbacks.py      enums.py       pnconfiguration.py  request_handlers
crypto_core.py    errors.py      pubnub_asyncio.py   structures.py
crypto_legacy.py  exceptions.py  pubnub_core.py      utils.py
crypto.py         __init__.py    pubnub.py           workers.py
dtos.py           managers.py    pubnub_tornado.py
pi@mirror:~/env/lib/python3.5/site-packages/python/pubnub $ 

I have it now in site_package/python

**Comment by mnail79** [comment]
What else?

**Comment by gauravsacc** [comment]
if you have pubnub and all packages correctly installed you should be able to run the script from the virtual environment.

**Comment by mnail79** [comment]
as you see, pubnub folder is not in site_package folder. its in site_package/python folder. May be I must uninstall pubnub and then install it again? How to uninstall pubnub?

**Comment by gauravsacc** [comment]
https://pip.pypa.io/en/stable/reference/pip_uninstall/

**Comment by mnail79** [comment]
the same error. Ok. Now i will format my sdcard and reinstall all from first step. And I will write here all my errors

**Comment by mnail79** [comment]
Can I install your product via putty, or only direct from raspberry terminal?

**Comment by gauravsacc** [comment]
You should be able to install via putty as well.

**Comment by mnail79** [comment]
Ok. I began from the first step. And now I am in Google Assistant Demo example.
It work fine. 
And there is written 

Next steps
You are now ready to start your own project:
git clone https://github.com/googlesamples/assistant-sdk-python
cp -r assistant-sdk-python/google-assistant-sdk/googlesamples/assistant/library new-project

Do I have to do this?

**Comment by mnail79** [comment]
in your documentation you whote
"Install Pubnub dependencies using pip install 'pubnub>=4.0.13'"
Do I have to do it from activated environment?
(env) pi@raspberrypi:~ $ python -m pip install 'pubnub>=4.0.13'
This way?

**Comment by mnail79** [comment]
ok. All is ok. I run /home/pi/env/bin/python3 -u assistant.py and can see the message "hello from phyton".

Then I add to config.js
{
    module: "MMM-GoogleAssistant",
    position: "top_right",
    config: {
        maxWidth: "100%",    
        header: ""
    }
},

and run npm start

pi@raspberrypi:~/MagicMirror $ npm start

> magicmirror@2.1.2 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.1.2
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-GoogleAssistant
All module helpers loaded.
Starting server on port 8080 ...
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-GoogleAssistant
Starting module helper: MMM-GoogleAssistant
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/d1ovvit9ing1vp58pv9o5lkp70%40group.calendar.google.com/private-20af06549b0da2de75ae6b2c954f509f/basic.ics - Interval: 300000
Create new news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000
now initializing assistant


I can see GoogleAssistant logo, but "OK Google, What is the weather today" is not working. No reaction, no answer. Why?

**Comment by gauravsacc** [comment]
are you sure you have both magic mirror server and python script running.

**Comment by mnail79** [comment]
I dont know. How can I check it? I run only npm start

**Comment by gauravsacc** [comment]
after running npm start, open another terminal window and launch the assistant script. home/pi/env/bin/python3 -u assistant.py

**Comment by mnail79** [comment]
ok. I will do it, and if it will be ok, what I have to do, put 2 command together in autostart?

**Comment by mnail79** [comment]
Yes. After running npm start, I opened another terminal window and launch assistant script. All is ok. And what i have to do? to run assistant script automatically, when MagicMirror is started

**Comment by gauravsacc** [comment]
Automatically launching assistant script on MagicMirror server startup isn't currently supported.
However, you can google on how to launch multiple scripts on your raspberry pi startup. 
Since this module is now working for you without any changes required I'm closing the issue.

**Comment by aro28** [comment]
![screenshot from 2018-01-08 15-05-37](https://user-images.githubusercontent.com/25077676/34664442-255f5b8e-f486-11e7-9bbb-7bccc284ab49.png)
Hi gauravsacc,
I have a same issue. I can see GoogleAssistant logo, but "OK Google, What is the weather today?" is not answering me. No reaction. Could you please advise what should i do? Your assistance is needed.

Thank you!

![screenshot from 2018-01-08 15-07-43](https://user-images.githubusercontent.com/25077676/34664439-1e6c84a0-f486-11e7-94f4-48e6ec635141.png)

**Comment by btw1004** [comment]
Hi I really need some help, I'm new to this so I apologize if I don't quite understand something.
So I've gotten pretty far already however when I get to the part where you have to run assistant.py I keep getting errors. 
If I try running assistant.py from the MagicMirror directory I get 
Traceback (most recent call last):
    File "/home/pi/MagicMirror/modules/MMM-GoogleAssistant/pi/assistant.py", line
25, in <module>
       import google.oauth2.credentials
ImportError: No module named google.oauth2.credentials

If I try to run the python3 -u assistant.py way it says "No such file or directory".

Please help, I've been going at this for hours and I'm just lost at this point.

**Comment by maikinmoves** [comment]
btw:  you have to activate the virtual environment first for python.

pi@pi:~ $ source env/bin/activate
(env) pi@pi:~$ /home/pi/env/bin/python3 -u assistant.py

**Comment by btw1004** [comment]
I got the same thing, "No such file or directory"

**Comment by maikinmoves** [comment]
have you added your google assistant credentials (which is displayed when you run the googlesamples-assistant-hotword --project-id ......     that credential is a long alphanumerical nonsense), and pubnub subscrib_key and publish_key to the assistant.py file under /home/pi/MagicMirror/modules/MMM-GoogleAssistant/pi/assistant.py

**Comment by btw1004** [comment]
Yes I've done that already, when I run the samples it works perfectly fine.

**Comment by btw1004** [comment]
I'm not really sure what else to do, can somebody please help me?
