### ISSUE TITLE
ImportError: No module named google.oauth2.credentials

### ISSUE THREAD

**Issue by London40** [gauravsacc/MMM-GoogleAssistant#12]
Hi gauravsacc,

Thank you so much for your work on this module, it's a great addition to see the visual input/ export of the google assistant on the Raspberry PI.

I am having an issue though, in running the module seemlessly with Magic Mirror and Google assistant Demo.

When i try to run the assistant.py i get the below error info:

Traceback (most recent call last):
File "assistant.py", line 24, in <module>
import google.oauth2.credentials
ImportError: No module named google.oauth2.credentials

Google assistant is running and all set up in a python env, and works. Followed all steps as best i can see for setup of the module and google assistant.

Not sure if i've missed something obvious.

Any help would be greatly appreciated.

Cheers

**Comment by gauravsacc** [comment]
See all closed issues here https://github.com/gauravsacc/MMM-GoogleAssistant/issues?q=is%3Aissue+is%3Aclosed
