### ISSUE TITLE
If you see a 'No module named google' error try running it via /home/pi/env/bin/python3 -u assistant.py

### ISSUE THREAD

**Issue by serhatkimya** [gauravsacc/MMM-GoogleAssistant#13]
İ can run Google Assistant without Magicmirror but i try to use with your module and i get this error always,
import google.oauth2.credentials
importError: No module named "google"

İsthere any solution? thanks

**Comment by abhisheksan** [comment]
i got the same error. i tried everything it is still not working

**Comment by gauravsacc** [comment]
Please see all closed issues here https://github.com/gauravsacc/MMM-GoogleAssistant/issues?q=is%3Aissue+is%3Aclosed
