### ISSUE TITLE
No logo reaction

### ISSUE THREAD

**Issue by kloboucek** [gauravsacc/MMM-GoogleAssistant#14]
Hi Gaurav,

I'd like to ask you for help (if your schedule allows of course). 

I'm running MM2 and I've successfully installed MMM-GA, too. The issue I'm having is that the logo won't animate into the "listening" mode whenever I say the hotword. Both apps are running at the same time, I tried starting the MMM-GA first and then launching MM2 and vice-versa, but with no luck.

There's one error msg I'm getting every time I launch MMM-GA and it looks like this:
_Exception in subscribe loop: HTTP Client Error (400): {"message":"Invalid Subscribe Key","error":true,"service":"Access Manager","status":400}

reconnection policy is disabled, please handle reconnection manually.__

I did add both sub and pub keys in all the three files as per your guide, but I'm still not sure whether this has anything to do with the icon animation in MM2.

Anyway, this is a brief description of what I've been experiencing so far and I'd very much appreciate any advice.

Thank you...
Kind regards...
Michal

**Comment by gauravsacc** [comment]
Hey this error is related to pubnub keys steup. Can you double check if you have all keys setup correctly.

> HTTP Client Error (400): {"message":"Invalid Subscribe Key","error":true,"service":"Access Manager","status":400}
