### ISSUE TITLE
How to update git pull not working 

### ISSUE THREAD

**Issue by sainiaj** [gauravsacc/MMM-GoogleAssistant#15]
Hi I tried updating by going to module dir and git pull however I get this error below 
pi@MagicMirror:~/MagicMirror/modules/MMM-GoogleAssistant $ git pullUpdating 84fe8fd..7d4fca5
fatal: Unable to create '/home/pi/MagicMirror/modules/MMM-GoogleAssistant/.git/index.lock': File exists.

If no other git process is currently running, this probably means agit process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.       pi@MagicMirror:~/MagicMirror/modules/MMM-GoogleAssistant

**Comment by gauravsacc** [comment]
@sainiaj this is not the issue with the MMM-GoogleAssistant. Try cleaning your local checkout folder and cloning the repo again.
