### ISSUE TITLE
Possible incompatability with new GoogleAssistant Update

### ISSUE THREAD

**Issue by teamreflect** [gauravsacc/MMM-GoogleAssistant#16]
Tried installing this module today and tried to make it with the work with new google assistant update.. I ran in to this following error code: 
```
  File "assistant.py", line 133, in <module>
    main()
  File "assistant.py", line 130, in main
    init_googleAssistant()
  File "assistant.py", line 124, in init_googleAssistant
    with Assistant(credentials) as assistant:
TypeError: __init__() missing 1 required positional argument: 'device_model_id'
hello from python!!
```
any ideas on what is causing the problem?

**Comment by elblogbruno** [comment]
I've got the same issue too
Maybe you need todo especify your model id you specified on the registering process on the new Google assistant SDK

**Comment by Raddy13** [comment]
Solved it!

The SDK update changed the assistant initiation call. You registered a device_model_id ("Raddys-magic-mirror-device-id" for example) in the [original instructions](https://developers.google.com/assistant/sdk/guides/library/python/embed/register-device), so you have to add that to the assistant.py file. ([Here are instructions](https://developers.google.com/assistant/sdk/reference/device-registration/model-and-instance-schemas#device_model_json) on manually registered a device and creating a device instance--I don't know if an instance is required for this to work, but it's part of what I did trying to solve this).

The current call is this:

```
with Assistant(credentials) as assistant:
```

In the updated method found on [Google's dev site](https://developers.google.com/assistant/sdk/reference/library/python/), it should read:

```
with Assistant(credentials, device_model_id) as assistant:
```
Where you replace device_model_id with whatever you registered before.

```
with Assistant(credentials, "Raddys-magic-mirror-device-id") as assistant:
```
Run it and it should work!

**Comment by elblogbruno** [comment]
Thanks a lot!
Now I'm working on making a sound wether you say Ok Google!
Sometimes you don't know if it has listened to you

**Comment by elblogbruno** [comment]
https://drive.google.com/file/d/1kJgWdBX3gN-mp7wFlCFAqFcZX_hUAQy-/view?usp=sharing
I'm using this sound!

**Comment by elblogbruno** [comment]
For anybody who wants to try just see my modded assistant.py

https://drive.google.com/file/d/1vWzqw4bJJdbnwuwylzD2UbmWTpjKVjzn/view?usp=sharing

**Comment by gauravsacc** [comment]
Hello, @teamreflect @elblogbruno @Raddy13 I haven't had time to implement the new SDK changes. 
@elblogbruno  Thanks for providing the mod as an alternative. Do you want to raise a PR to this project? I can merge your changes.

**Comment by elblogbruno** [comment]
Ok no problem!
Glad you like It!

**Comment by elblogbruno** [comment]
Wherever I arrive home I'll do It!

**Comment by aro28** [comment]
hi  @elblogbruno  and @elblogbruno 
Currently, GoogleAssistant works for me, but there're two issues
1. It works only if i run assistant.py in separate terminal. Yes. You already mentioned about this issue and need to check SDK.
2. GoogleAssisntant answering me and i do not understand what languages is.
![screenshot from 2018-01-10 02-56-42](https://user-images.githubusercontent.com/25077676/34742856-e8f26ae2-f5b1-11e7-97d4-18302500b0a8.png)

**Comment by elblogbruno** [comment]
Actually I use a code that runs assistant.py on background wheter I reboot the pi , the assistant.py runs and works!
I do not have and answer for the second problem sorry!

**Comment by aro28** [comment]
Hi @elblogbruno It answers the same sentence, to any of my questions: "speech recognition can help you"
Any ideas? Maybe i should enable some others APIs?

**Comment by aro28** [comment]
Yahoo!!! I fixed it.

**Comment by aro28** [comment]
Resolved.
Resolution: Configure Google Account and Voice/Speech recognition with proper language.

**Comment by jazzkitt** [comment]
@elblogbruno 
I have been working on getting the Assistant to work on the mirror. Thanks to you and @gauravsacc and all others that helped me, i am almost there. Here is my issue, in the above comments you mentioned that

> "Actually I use a code that runs assistant.py on background wheter I reboot the pi , the assistant.py runs and works!"


What are you using to achieve this automation. I am able to run Assistant using assistant.py using the environment.
