### ISSUE TITLE
Noob Question with everything working

### ISSUE THREAD

**Issue by akiratwang** [gauravsacc/MMM-GoogleAssistant#17]
I've just done a fresh reinstall of Debian-Stretch and the current google SDK. They've added a few new steps (like registering your device and projects) and the demo works flawlessly. I've been able to successfully install this module alongside magic mirror and have it appear on the screen. Now, I've read this issue (https://github.com/gauravsacc/MMM-GoogleAssistant/issues/11) but i still fail to see how i should run the assistant.py (really sorry i have no idea how to run this). Thanks in advance and great work so far :))

**Comment by akiratwang** [comment]
Update: I ran it through the /home/pi/env/bin/python3 -u assistant.py but got either pubnub or google module errors. I checked to see if it was in the /env/lib but it was not there, despite installing it correctly using pip install 'pubnub>=4.0.13'

**Comment by gauravsacc** [comment]
You can run assistant.py using the following command
`home/pi/env/bin/python3 -u assistant.py`
You should be running assistant.py script in the virtual environment. Also, be sure to install pubnub dependencies in the virtual environment.

**Comment by akiratwang** [comment]
Oh okay so run the environment then install pubnub? I think that's where I went wrong then. Thanks :))

**Comment by nitrogen73** [comment]
How can I run assistant.py?

Im getting these error?

![untitled](https://user-images.githubusercontent.com/35220323/34669680-48462c8a-f48c-11e7-824f-62845efcd93e.jpg)

**Comment by gauravsacc** [comment]
@nitrogen73 please see all closed issues https://github.com/gauravsacc/MMM-GoogleAssistant/issues?q=is%3Aissue+is%3Aclosed 
it doesn't look like you have python installed in your virtual environment.

**Comment by gauravsacc** [comment]
@akiratwang please close the issue if its working now.

**Comment by nitrogen73** [comment]
@gauravsacc could you please close this... I can't see the option for closing the issue... now its working for me
