### ISSUE TITLE
I can see Google Logo, but nothing happens on "OK Google, what's the weather today?"

### ISSUE THREAD

**Issue by aro28** [gauravsacc/MMM-GoogleAssistant#18]
![screenshot from 2018-01-08 15-07-43](https://user-images.githubusercontent.com/25077676/34666413-856a9540-f48e-11e7-8766-ca2fd56420e7.png)
Hello,
I need your help. Currently, MM is running and Google Logo is appearing, python3 works.

"Hello, How can i help?" animates is not activated using the hotword 'Ok Google'.
My limited brain is exhausted now. Please help.
![screenshot from 2018-01-08 15-05-37](https://user-images.githubusercontent.com/25077676/34666410-81c570fe-f48e-11e7-8034-d45f755ab284.png)

**Comment by nitrogen73** [comment]
Im also facing the same problem... Can anyone help please....?

**Comment by aro28** [comment]
Currently, Google Assistant is responding me in ENV.. i assume ii need to add Handle Commands on the Device. Will try to add later once i return.
![screenshot from 2018-01-08 17-28-17](https://user-images.githubusercontent.com/25077676/34668999-ebe4fcec-f499-11e7-8845-82f6f77b6737.png)

**Comment by aro28** [comment]
Currently, Google Assistant is responding me in ENV.. i assume ii need to add Handle Commands on the Device. Will try to add later once i return.
![screenshot from 2018-01-08 17-28-17](https://user-images.githubusercontent.com/25077676/34669069-3813b48c-f49a-11e7-9568-6c0e14c161c3.png)

**Comment by nitrogen73** [comment]
For me also its works in the virtual environment... But in the mirror it doesn't...

Bro..you just go through the below link...

https://github.com/gauravsacc/MMM-GoogleAssistant/issues/11

here it says both mirror and assistant.py should work together... But how can i run assistant.py??

**Comment by nitrogen73** [comment]
In env it gives me answers... but in mirror google assistant is inactive...

**Comment by gauravsacc** [comment]
see this issue here https://github.com/gauravsacc/MMM-GoogleAssistant/issues/16
The new SDK update introduces another param. Please use the modded version of the assistant.py until that change is merged. Thankyou!
The ReadMe.md file of this project also highlights that this hasn't been tested with the new SDK update.  I'll have time this weekend to test the compatibility with the new SDK

**Comment by aro28** [comment]
Interesting, why i do not receive answers?! Any idea? I'm a beginner in programming.

**Comment by aro28** [comment]
Thank you @gauravsacc ..
We are looking forward to the results of your work. You are doing a great job.

**Comment by nitrogen73** [comment]
for me it works perfect... yesterday i made it...

**Comment by nitrogen73** [comment]
from the screenshot you uploaded i think GA works perfectly in env.. 
Next you have to install pubnub 
then execute the assistant.py. You have to download moded "Assistant.py"
(yesterday i downloaded it from some links. But now i cant see that. give me your mail id i can forward it to you)
Next you have to Replace keys in Assistant.py and you have to enter the device model id in the Assistant.py ( in line 124, im not sure about the line please check)
then Copy the moded Assistant.py to the pi home directory
Open terminal and run following command
/home/pi/env/bin/python3 -u /home/pi/Assistant.py
then start  the magicmirror in env. 

tell me if it works

**Comment by aro28** [comment]
Hi @nitrogen73 
Now it seems it works.
Please check below. Should it answer to me? I asked about weather... 
![assitant py](https://user-images.githubusercontent.com/25077676/34737426-56684ff4-f5a0-11e7-8aef-10af3b9d98f0.png)

**Comment by nitrogen73** [comment]
Yes its working... there is no sound from your speaker?

**Comment by aro28** [comment]
NO. I don't hear

**Comment by nitrogen73** [comment]
How you connected your mic? Sound card or by usb mic?

**Comment by aro28** [comment]
I use usb sound hub.  I configured and tested. It works.
pi@mymirror:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by aro28** [comment]
![screenshot from 2018-01-10 01-04-19](https://user-images.githubusercontent.com/25077676/34738106-36673344-f5a2-11e7-96d7-b6ee653011fc.png)

I tested and it works.

**Comment by nitrogen73** [comment]
Install pulse audio and run the comand pavucontrol in terminal ... then one window will open... in that go to output device... then run your GA in env ... in there you can see sound for that is muted or not...

**Comment by nitrogen73** [comment]
To install pulse audio

sudo apt-get install pulseaudio

**Comment by nitrogen73** [comment]
In some cases the sound mixer will mute the sound only for GA that we are running... it happened to me...

**Comment by aro28** [comment]
pi@mymirror:~ $ pavucontrol
-bash: pavucontrol: command not found
pi@mymirror:~ $ sudo pavucontrol
sudo: pavucontrol: command not found
pi@mymirror:~ $

**Comment by nitrogen73** [comment]
Before running pavucontrol you have to install pulse audio

**Comment by nitrogen73** [comment]
sudo apt install pulseaudio pavucontrol

**Comment by aro28** [comment]
yes. finally i'm hearing..
It's answering.. But do not know answers :) :)
![screenshot from 2018-01-10 01-14-05](https://user-images.githubusercontent.com/25077676/34738558-93673638-f5a3-11e7-9219-f88f0c0634ad.png)

**Comment by aro28** [comment]
It seems It's speaking/answering in Spanish. How to check if it's English or not?

**Comment by nitrogen73** [comment]
Kudos... did you install pulse audio?

**Comment by aro28** [comment]
Yes. I've installed it.. But  i skipped pavucontrol.. NOw installing

**Comment by nitrogen73** [comment]
No idea... better google it..

**Comment by aro28** [comment]
Resolved.

**Comment by nitrogen73** [comment]
Bro can i have your mail id... I would like to be in touch with you, i need your support in this... now I'm working with Alexa to bring in the magicmirror... and im facing some issues... I think you can help me in this... you can mail in kvnpaul73@gmail.com

**Comment by aro28** [comment]
Sure.

**Comment by gauravsacc** [comment]
@aro28 looks like its working for you now. Should I close the issue?

**Comment by afroguys** [comment]
it is possible to change the hotword from 'Ok Google' to others??

**Comment by PanicLion** [comment]
Mine is stuck on "hello from python"

**Comment by rahulpalnitkar9** [comment]
Where can I download moded 'Assistant.py'?
