### ISSUE TITLE
Good Job! but some opinions.

### ISSUE THREAD

**Issue by eouia** [gauravsacc/MMM-GoogleAssistant#2]
When I activate `assistant.py` and say nothing for a while, I meet the error `mic_failure_detector.cc(120)] Channel 1 has failed. Powers -inf and -inf`.
I doubt it could be related with my `.asoundrc` configuration. Anyway, Google-Assistant-SDK is somehow not stable, I think. (Can you show your `.asoundrc` ?)

And I believe you can make `assistant.py` to start on module loading(and shown status), and to kill on module hidden(or some stop notification). It will be more convenient in MM.

Anyway, Pubnub is a great idea. But I found something nice.
Did you try `Dataplicity`? `Dataplicity` and `nginx reverse proxy` enables the RPI to get a permanent URL domain and virtual(?) https. It means, Actions on Assistant can be directly implemented in the RPI without any external server for webhooking.
I hope I could build my own, but I still have a problem of sound configuration, so I couldn't start yet. I suggest you try this feature in your module.(or another new)

**Comment by ubilb72** [comment]
Hi @gauravsacc, great job. I tried it and worked perfectly. I'm looking forward the upcoming improvements in your module. I'll appy them as soon as you get it.

@eouia, this is the content of my .asoundrc configuration file:

pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
}
pcm.mic {
  type plug
  slave {
    pcm "hw:0,0"
  }
}
pcm.speaker {
  type plug
  slave {
    pcm "hw:1,0"
  }
}

I hope it works for you.

Regards

**Comment by gauravsacc** [comment]
@eouia are you still facing issues? If not I'd like to close this issue.
I haven't tried Dataplicity yet and yes nginx seems a better alternative to ngrok. Thanks for pointing out these tools. I'll take a look.

**Comment by eouia** [comment]
@gauravsacc @ubilb72 
Thank you all commenting. I can use your suggestion for my use.
I'll close this issue. thanks again.
