### ISSUE TITLE
Google assistant language support

### ISSUE THREAD

**Issue by aro28** [gauravsacc/MMM-GoogleAssistant#21]
Hello,
Does anybody knows how to change GA speech language on Magic Mirror?
Thanks in advance.
Best,

**Comment by gauravsacc** [comment]
@aro28 the new sdk update does support more languages but I haven't had a chance to look into the changes/features yet. Adding an enhancement label

**Comment by aro28** [comment]
Hi,
can you suggest me which file i need to look into the changes/features?

**Comment by gauravsacc** [comment]
@aro28 here are the official release notes https://developers.google.com/assistant/sdk/release-notes. What exactly are you trying to do? You should be able to go tor you Google Assistant settings on your phone and change language settings there.

**Comment by aro28** [comment]
hi @gauravsacc 
I'm trying to adapt MMM-GoogleAssistant for my native language, which is supporting by GA.
I've changed my google account language preferences and Voice recognition works only on PC, Tablets and phones, but not in MM. MMM-GoogleAssistant  supports only English on MM. 
Any ideas?
Thank you in advance!
Best,

**Comment by aro28** [comment]
ok. just read on provided link that i need to change language on Google Assistant app on Android to iOS.
There's no GA app on my iOS 11.2.2 version. I will check on Android. Let you know later about result.

**Comment by aro28** [comment]
I've installed GA app on iPhone and unfortunately it supports only English(US, UK, AUS, Can), Deutsch, Francias(France and Canada) and Chinese.

![img_2972](https://user-images.githubusercontent.com/25077676/34920086-451ec20a-f997-11e7-9e1b-8f2e674f369e.jpg)

**Comment by gauravsacc** [comment]
well, unfortunately, you have to wait until your language is officially supported by GA.
