### ISSUE TITLE
Hard to understand my error: TypeError: __init__() got an unexpected keyword argument 'installed'

### ISSUE THREAD

**Issue by jmrandby** [gauravsacc/MMM-GoogleAssistant#24]
Trying to run assistant.py

(env) pi@raspberrypi:~/MagicMirror/modules/MMM-GoogleAssistant $ python3 pi/assistant.py 
pubnub subscription completed
Traceback (most recent call last):
  File "pi/assistant.py", line 131, in <module>
    main()
  File "pi/assistant.py", line 128, in main
    init_googleAssistant()
  File "pi/assistant.py", line 121, in init_googleAssistant
    credentials = google.oauth2.credentials.Credentials(token=None,**json.load(f))
TypeError: __init__() got an unexpected keyword argument 'installed'
hello from python!!

I am running the assistant in the virtual environment that I use for the voice-recognizer-raspi. Any idea what could be wrong?my

**Comment by gauravsacc** [comment]
are you still running into issues or this is resolved?

**Comment by jmrandby** [comment]
Still problem.

**Comment by afroguys** [comment]
**my problem already solved.**

i got this error .... what i miss??

_(env) pi@raspberrypi:~/.config $ googlesamples-assistant-devicetool list --help
Error: Error loading credentials: __init__() got an unexpected keyword argument 'installed'.
Run google-oauthlib-tool to initialize new OAuth 2.0 credentials.
_
