### ISSUE TITLE
error after updating

### ISSUE THREAD

**Issue by sainiaj** [gauravsacc/MMM-GoogleAssistant#25]
hi i am getting following error after updating the module, can someone please help the  
the only change i have made is added the private and published key,

am i missing any steps 

Traceback (most recent call last):
  File "assistant.py", line 31, in <module>
    from pubnub.callbacks import SubscribeCallback
ImportError: No module named 'pubnub'

**Comment by gauravsacc** [comment]
@sainiaj please see all closed issues. It could be because you are not running the script in the correct environment.
