### ISSUE TITLE
Extremely slow respone

### ISSUE THREAD

**Issue by aech-git** [gauravsacc/MMM-GoogleAssistant#27]
Its running but it wont respond until i say the keyword again then it cuts off and goes back in to another loop.  

` python assistant.py
pubnub subscription completed
hello from python!!
[14109:14135:ERROR:assistant_nupnp_client.cc(103)] Cloud discovery nupnp request failed: [60] Peer certificate cannot be authenticated with given CA certificates
[14109:14135:ERROR:assistant_nupnp_client.cc(103)] Cloud discovery nupnp request failed: [60] Peer certificate cannot be authenticated with given CA certificates
[14109:14135:ERROR:assistant_nupnp_client.cc(103)] Cloud discovery nupnp request failed: [60] Peer certificate cannot be authenticated with given CA certificates
Playing WAVE 'start.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo

ON_CONVERSATION_TURN_STARTED

ON_RECOGNIZING_SPEECH_FINISHED : what movies are playing in Ada Oklahoma

ON_CONVERSATION_TURN_FINISHED
Playing WAVE 'start.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo

ON_CONVERSATION_TURN_STARTED

ON_RECOGNIZING_SPEECH_FINISHED : what time is it

Playing WAVE 'start.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
ON_CONVERSATION_TURN_FINISHED

ON_CONVERSATION_TURN_STARTED

ON_RECOGNIZING_SPEECH_FINISHED : goodbye

ON_CONVERSATION_TURN_FINISHED
Playing WAVE 'start.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo

ON_CONVERSATION_TURN_STARTED

ON_RECOGNIZING_SPEECH_FINISHED : what time is it

`

**Comment by gauravsacc** [comment]
The google assistant SDK requires a keyword/hardware trigger after one conversation is finished. This is working as designed/developed

**Comment by aech-git** [comment]
@gauravsacc Ok well... the voice activation works fine using the sample code from
google when setting it all up but when I run assistant.py I say ok google
what time is it? The console shows the text but she does not respond until
I say ok google again
