### ISSUE TITLE
Video or info how this module works

### ISSUE THREAD

**Issue by E3V3A** [gauravsacc/MMM-GoogleAssistant#29]
Do you have a Video or some other info how this module works?
* What kind of response can we expect? 
* If I ask: `Show me some cat pictures?`, then what happens? 
* Can I see them, or its voice only?
* What are the dependencies? (I.e. can I just install this MMM and then it works?)

**Comment by Kennz0r** [comment]
i'm sorry but everything you just asked is in the readme so just read it.

**Comment by gauravsacc** [comment]
@E3V3A its voice only. All dependencies and installation process is documented in readme. Let me know if you are facing specific issues along with the log/console output

**Comment by E3V3A** [comment]
I just want to know what it does! You even put a "placeholder for video" in the readme. 
And if I asked the question above, what would happen? (That surely isn't written in the readme!) 

Anyway, I see you're not very keen of having other people being able to use this module.
I'm not jumping through the hoops of installing something without knowing what it does.

**Comment by Kennz0r** [comment]
Nothing would happen if you asked for a cat picture because it doesnt have a "screen" right now. it's only voice as stated in the answer you already got and in the readme.
![myass](https://user-images.githubusercontent.com/37302430/37388726-e30a47bc-2761-11e8-904e-c4f8db604629.png) please.
