### ISSUE TITLE
No module named 'google' No module named 'pubnub'

### ISSUE THREAD

**Issue by Kolk123** [gauravsacc/MMM-GoogleAssistant#3]
i did all the steps but cant figure it out.
i tried this
pi@raspberrypi:~/MagicMirror/modules/MMM-GoogleAssistant/pi $ python3 -u assistant.py
Traceback (most recent call last):
  File "assistant.py", line 47, in <module>
    import google.oauth2.credentials
ImportError: No module named 'google'

and tried this
(env) pi@raspberrypi:~/env/bin $ python3 -u assistant.py
Traceback (most recent call last):
  File "assistant.py", line 47, in <module>
    import google.oauth2.credentials
ImportError: No module named 'google'

i want running the program because Alexa didnt work well..
this is my first rasp/python project and happy that my mirror works well. this makes it complete

greetz roy

**Comment by gauravsacc** [comment]
@Kolk123 are you able to run google-assistant-demo here https://developers.google.com/assistant/sdk/develop/python/run-sample

**Comment by Kolk123** [comment]
@gauravsacc thanx for response yes I did and the wake word works..

**Comment by akiratwang** [comment]
Hey! Great work so far :)
Same issue here - I've gotten google SDK to work as a demo (manual installation) but instead I get this:

(env) pi@raspberrypi:~/env/bin $ python3 -u assistant.py
Traceback (most recent call last):
File "assistant.py", line 26, in <module>
from google.assistant.library import Assistant
ImportError: No module named assistant.library

**Comment by Kolk123** [comment]
if installed it all again.. run the demo and works great. now try to run the assistant.py other line problem

(env) pi@raspberrypi:~/env/bin $ python3 -u assistant.py
Traceback (most recent call last):
  File "assistant.py", line 24, in <module>
    import google.oauth2.credentials
ImportError: No module named 'google'

greetz roy

**Comment by akiratwang** [comment]
@kolk123 
Did you by any chance forget to install the dependencies manually with sudo npm install in the MMM-GoogleAssistant Directory? And yeh I got the module to be authorised but now python refused to access the assistant.py

**Comment by gauravsacc** [comment]
Try this 
1. Close all terminal windows that you have open (deactivate all python virtual environments)
2. Copy assistant.py to the pi home directory
3. Open terminal and run following command 
 `/home/pi/env/bin/python3 -u /home/pi/assistant.py`

**Comment by akiratwang** [comment]
will be redoing a clean installation and installing MMM-GA before twinking with any other settings or config - will update on status soon

**Comment by Kolk123** [comment]
@akiratwang  yes if installed it with sudo
@gauravsacc  when im using this code after closing everything and reboot i get this
/home/pi/env/bin/python3: can't open file 'assistant.py': [Errno 2] No such file or directory

**Comment by gauravsacc** [comment]
@Kolk123 well that error means you don't have assistant.py in the /home/pi/ folder. You sure you have it there?

**Comment by akiratwang** [comment]
ok so I've done a fresh install without touching anything except this module. Following the current steps:

pi@raspberrypi:~ $ sudo pip install 'pubnub>=4.0.1'
Downloading/unpacking pubnub>=4.0.1
  Downloading pubnub-4.0.12.tar.gz
  Running setup.py (path:/tmp/pip-build-zoKQBh/pubnub/setup.py) egg_info for package pubnub
    
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.3 in /usr/local/lib/python2.7/dist-packages (from pubnub>=4.0.1)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.4 in /usr/lib/python2.7/dist-packages (from pubnub>=4.0.1)
Requirement already satisfied (use --upgrade to upgrade): six>=1.10 in /usr/local/lib/python2.7/dist-packages (from pubnub>=4.0.1)
Installing collected packages: pubnub
  Running setup.py install for pubnub
      File "/usr/local/lib/python2.7/dist-packages/pubnub/pubnub_asyncio.py", line 82
        envelope = yield from self._request_helper(options_func, cancellation_event)
                            ^
    SyntaxError: invalid syntax
    
    
Successfully installed pubnub
Cleaning up...

//pubnub>=4.0.13 does not seem to exist so ive left it with 4.0.1
pi@raspberrypi:~ $ /home/pi/env/bin/python3 -u /home/pi/assistant.py
Traceback (most recent call last):
  File "/home/pi/assistant.py", line 30, in <module>
    from pubnub.callbacks import SubscribeCallback
ImportError: No module named 'pubnub'

//furthermore, we know the assistant works
pi@raspberrypi:~ $ source env/bin/activate
(env) pi@raspberrypi:~ $ google-assistant-demo
ON_MUTED_CHANGED:
  {'is_muted': False}
ON_START_FINISHED

//and the original module problem still exists:
pi@raspberrypi:~/MagicMirror/modules/MMM-GoogleAssistant/pi $ python assistant.py
Traceback (most recent call last):
  File "assistant.py", line 24, in <module>
    import google.oauth2.credentials
ImportError: No module named google.oauth2.credentials

any extra details that may matter:
everything is done and installed directly from the pi (did not use SHSH)

**Comment by gauravsacc** [comment]
@akiratwang  can you check if pubnub is installed correctly in your virtual environment 


```
pi@raspberrypi:~ $ source env/bin/activate
(env) pi@raspberrypi:~ $ pip show pubnub
```


It should give you an output similar to this -

> Name: pubnub
> Version: 4.0.12
> Summary: PubNub Real-time push service in the cloud
> Home-page: http://pubnub.com
> Author: PubNub
> Author-email: support@pubnub.com
> License: MIT
> Location: /home/pi/env/lib/python3.4/dist-packages
> Requires: requests, pycryptodomex, six

If not then install pubnub in the virtual environment 
`(env) pi@raspberrypi:~ $ pip install pubnub`

Once it's installed exit the virtual environment and run the command
`pi@raspberrypi:~ $ /home/pi/env/bin/python3 -u /home/pi/assistant.py`

**Comment by akiratwang** [comment]
@gauravsacc assistant.py now runs (confirmation message: hello from python!). do i leave this running in conjunction to mm2 at all times? thanks so much by the way!

**Comment by gauravsacc** [comment]
Yes, leave it running and enjoy your Magic Mirror powered by GoogleAssistant :)
Closing the issue!

**Comment by Kolk123** [comment]
Why your closing the issue ? If start it not him.. gonna try yoir last options later. If it doesn't work I'm done with it and staying in alexa

**Comment by gauravsacc** [comment]
@Kolk123 I believe it's the same problem. Anyways I'm re-opening the issue, let me know if you still see issues. Happy to help!

**Comment by akiratwang** [comment]
Well worst case try a fresh install like I did? Inb4 installs to node_modules directory instead of modules

**Comment by Kolk123** [comment]
if done a clean install. checkt pubnub. placed assistant.py in home/pi  but error code is not gone

pi@raspberrypi:~ $ /home/pi/env/bin/python3 -u /home/pi/assistant.py
Traceback (most recent call last):
  File "/home/pi/assistant.py", line 24, in <module>
    import google.oauth2.credentials
ImportError: No module named 'google'

**Comment by gauravsacc** [comment]
@Kolk123  and you are able to run google-assistant-demo sample?
 If yes, can you confirm if you are able to launch assistant via the following command as well. 
`pi@raspberrypi:~ $ /home/pi/env/bin/python3 /home/pi/env/bin/google-assistant-demo`

**Comment by chribiza** [comment]
How can we make it run on startup of the mirror ??
I have allready installed pm2 ....
Thank you

**Comment by Kolk123** [comment]
formatted the sd card and installed all new.. work like a charm!! now my display died but thanks for all the help!!!

**Comment by Krisalexroberts** [comment]
Apt-get upgrade fixes this too

**Comment by DJB1966** [comment]
Im also having the same problem i used this guide [https://emailparthdhingra.wixsite.com/magicmirrorassistant] and I'm getting this error File "assistant.py", line 26, in
from google.assistant.library import Assistant
ImportError: No module named assistant.library
I know this post is old but hoping someone can help
