### ISSUE TITLE
Error when run assistant.py at env

### ISSUE THREAD

**Issue by afroguys** [gauravsacc/MMM-GoogleAssistant#30]
hello, 

i got this error when try to running assistant.py using env.

_(env) pi@raspberrypi:~ $ /home/pi/env/bin/python3 -u assistant.py
Traceback (most recent call last):
  File "assistant.py", line 31, in <module>
    from pubnub.callbacks import SubscribeCallback
ImportError: No module named 'pubnub'
_

**Comment by gauravsacc** [comment]
please check all closed issues. This is already resolved.

**Comment by varadwattamwar** [comment]
@gauravsacc 
My sample code works fine. I changed my subscribe key and public key in assistant.py also I entered magic-mirror-device-id and after running assistant.py I receive msgs: pubnub subscription completed and hello from python!! but there is no response from google assistant , google assistant does not work.
PLease help me out. Thanks in advance.
