### ISSUE TITLE
Pre-requisite for MMM-GoogleAssistant integration

### ISSUE THREAD

**Issue by werdnllac** [gauravsacc/MMM-GoogleAssistant#31]
Hi, I like to find the require version for integrating MMM-GoogleAssistant. Please advice the version needed. 

- Nodejs
- npm
- Rasbian

Thanks

**Comment by anooproy** [comment]
Hie all, can any one help with the GA authentication 
![mmm-ga](https://user-images.githubusercontent.com/38277408/39677843-b58c89d6-5136-11e8-89ab-7e3d9f9d51c8.jpg)

**Comment by gauravsacc** [comment]
You can try running with the latest versions and report back any incompatibility issues
