### ISSUE TITLE
Magic Mirror don't load the image

### ISSUE THREAD

**Issue by datrix88** [gauravsacc/MMM-GoogleAssistant#36]
Hi!
The script works fine: assystant.py run without problems.

I have a problem with the MM module. The images "assistant_active.png" and "assistant_inactive.png" are not loaded on Magic Mirror dashboard:

![image](https://user-images.githubusercontent.com/22351479/39727530-54baa746-5253-11e8-81e2-196ad44dca3a.png)

I saw the path of the png files into MMM-GoogleAssistant.js and is correct.
Can you help me?

Thanks!

**Comment by datrix88** [comment]
I resolved the problem with a new clone of the git. Thanks anyway.

**Comment by anooproy** [comment]
I have problem with 'No module named google' error help me to sort it out.
Thanks/
