### ISSUE TITLE
assistant.py error out

### ISSUE THREAD

**Issue by rahul1990bhatia** [gauravsacc/MMM-GoogleAssistant#37]
Hi,

when I am trying to run assistant.py I am getting following error
python assistant.py 
Traceback (most recent call last):
  File "assistant.py", line 27, in <module>
    from google.assistant.library import Assistant
ImportError: No module named 'google.assistant.library'

**Comment by rahul1990bhatia** [comment]
missed this:

pip install --upgrade google-assistant-library

**Comment by varadwattamwar** [comment]
@rahul1990bhatia 
My sample code works fine. I changed my subscribe key and public key in assistant.py also I entered magic-mirror-device-id and after running assistant.py I receive msgs: pubnub subscription completed and hello from python!! but there is no response from google assistant , google assistant does not work.
PLease help me out. Thanks in advance.
