### ISSUE TITLE
autostart with rpi

### ISSUE THREAD

**Issue by sainiaj** [gauravsacc/MMM-GoogleAssistant#4]
first of fall,

I would like to thank you for building this awesome module,
keep up the good work,

i was wondering if their is anywhere to make this auto start on boot
please note i am noob and requires step by step instructions ;(

even while setting up google assistant i got stuck few times but work now :)

in order for me to launch it i have to manfully enter these 2 cmds below

cd /home/pi/MagicMirror/modules/MMM-GoogleAssistant
source env/bin/activate  
cd /home/pi/MagicMirror/modules/MMM-GoogleAssistant/pi
python3 -u assistant.py

**Comment by gauravsacc** [comment]
@sainiaj Thanks. You can create a shell script to execute those commands and launch that script on startup. Here's an example how to do that https://raspberrypi.stackexchange.com/questions/8734/execute-script-on-start-up

**Comment by sainiaj** [comment]
Hi gauravsacc,

can you tell me what to write in the shell script sorry i am super noob 
do i write this word to word
cd /home/pi/MagicMirror/modules/MMM-GoogleAssistant
source env/bin/activate
cd /home/pi/MagicMirror/modules/MMM-GoogleAssistant/pi
python3 -u assistant.py

also do i use this method >>>Navigate to ~/.config/lxsession/LXDE-pi

or this one >>> /etc/rc.local

**Comment by Krisalexroberts** [comment]
It's not really helpful, I've tried all of these methods and none work.
