### ISSUE TITLE
Google Authorization Code Error 500

### ISSUE THREAD

**Issue by katherinemyersLPD** [gauravsacc/MMM-GoogleAssistant#44]
While trying to get an authorization code, I plug the provided URL into my search bar and instead of getting a code, I get 
"500. That’s an error.

There was an error. Please try again later. That’s all we know."
from Google.
I am inputing
google-oauthlib-tool --scope https://www.googleapis.com/auth/assistant-sdk-prototype \
>       --scope https://www.googleapis.com/auth/gcm \
>       --save --headless --client-secrets /home/pi/client_secret_id.json
into my terminal.
I have successfully done this before using the same Pi, computer, and terminal and have never run into this error

**Comment by gauravsacc** [comment]
this is a bug in the sdk itself https://github.com/googlesamples/assistant-sdk-python/issues/277
