### ISSUE TITLE
Custom actions

### ISSUE THREAD

**Issue by LorenzoZappa** [gauravsacc/MMM-GoogleAssistant#45]
Hello, I have successfully installed your module and everything is working like a charm (thank you very much for your work).
However lately I created some custom actions using google assistant sdk, and they work perfectly with google assistant. The issue is that they don't seem to work with this module. If I invoke my custom action the google assistant module recognize it as a know action (so far so good) but it doesn't run the commands saved in my hotword.py file.
I basically don't know where to save that file in order to get recognized and used.
Thank you for your help
Lorenzo

**Comment by gauravsacc** [comment]
@LorenzoZappa can you give me more details - where and what custom commands have you saved that you are trying to run

**Comment by LorenzoZappa** [comment]
Thank you for answering
I created some custom actions using google assistant sdk (following this guide: https://developers.google.com/assistant/sdk/guides/library/python/extend/add-trait-and-handler), and they work perfectly with google assistant, this is the command I use (from ~/assistant-sdk-python/google-assistant-sdk/googlesamples/assistant/library):

`python hotword.py --device_model_id my-model`

But if I try to use this module instead I get my actions recognised as registered. To register them I used the command:

`./gactions update --action_package actions.json --project project_id`

But they don't do anything that is written in my hotword.py file in this directory:

`~/assistant-sdk-python/google-assistant-sdk/googlesamples/assistant/library/hotword.py`

I think I have to copy and save that file to somewhere else, but I don't know where...
Thank you

**Comment by gauravsacc** [comment]
@LorenzoZappa hotword.py is a different script than the assistant.py that's used in this project.
You'll have to update those commands/scripts in the assistant.py.

**Comment by LorenzoZappa** [comment]
Where is the assistant.py default location so that I can update it?
Thank you very much for your help

**Comment by nikhil-gupta89** [comment]
@LorenzoZappa : It should be under /modules/MMM-GoogleAssistant/pi folder.

**Comment by LorenzoZappa** [comment]
@nikhil-gupta89 thank you very much, I found it and everything is working like a charm!
