### ISSUE TITLE
Will there be Snowboy/custom hotword support?

### ISSUE THREAD

**Issue by YangVincent** [gauravsacc/MMM-GoogleAssistant#46]

**Comment by gauravsacc** [comment]
hey @YangVincent there are other modules supporting the snowboy/custom hotword.

**Comment by YangVincent** [comment]
true, but they have to be linked with your file running pubsub, no? Would they work as long as they're running in parallel?

**Comment by gauravsacc** [comment]
If you want a custom hotword I'll recommend using the other modules and not this one.
