### ISSUE TITLE
Register Ga device

### ISSUE THREAD

**Issue by oceank82** [gauravsacc/MMM-GoogleAssistant#47]
Hello!

im stuck at:
Register your GA device using the register-tool available here and replace the magic-mirror-device-id in the assistant.py with your unique device id https://developers.google.com/assistant/sdk/reference/device-registration/device-tool

so how do I do that? is it the sam as going to device registration at the actions on google?(https://console.actions.google.com/)

**Comment by nikhil-gupta89** [comment]
@oceank82, Yes, it is the same as registering your device at Google Actions.
