### ISSUE TITLE
No module called google.assistant.library

### ISSUE THREAD

**Issue by csoler11** [gauravsacc/MMM-GoogleAssistant#59]
Hello I'm a very noob and I don't know how to download the sript, when i thing that i was doing well some error gets in the way and doesn't let me finish, the last time I provided it with sudo /assistant.py it tells me that there is no module called google.assistant.library. I followed all the steps without skipping anything, I need to finish the mirror, it is for a school job that I have to deliver in mid-September, thanks for the help.

**Comment by csoler11** [comment]
I try the other option that you put and it dosen't work

**Comment by diegopamio** [comment]
So, why is this issue closed?
