### ISSUE TITLE
Audio Input error - Works in Google-Assistant-Demo

### ISSUE THREAD

**Issue by ynn3k** [gauravsacc/MMM-GoogleAssistant#6]
pi@raspberrypi:~ $ sudo /home/pi/env/bin/python -u /home/pi/assistant.py
    pubnub subscription completed
    hello from python!!
    [2055:2080:ERROR:audio_input_processor.cc(755)] Input error
    [2055:2085:ERROR:audio_input_processor.cc(755)] Input error

**Comment by ynn3k** [comment]
disreguard

**Comment by javaj0hn** [comment]
@ynn3k how did you resolve this?
