### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by lordroi29** [gauravsacc/MMM-GoogleAssistant#65]
I've done everything correctly and I'm on the last step but when I tried to run the assistant.py file, I get a syntax error...

pi@raspberrypi:~ $ /home/pi/env/bin/python3 -u assistant.py
  File "assistant.py", line 61
    pubnub.publish().channel("magicmirror").message("hello from python!").async(my_publish_callback)
                                                                              ^
SyntaxError: invalid syntax
pi@raspberrypi:~ $

**Comment by altamashqureshi9144** [comment]
same error pls help

**Comment by reubenvickers** [comment]
I fixed this by changing all '.async's in the file with '.pn_async'. It seems the publish method was renamed

Reference: https://github.com/gauravsacc/MMM-GoogleAssistant/issues/51

**Comment by lordroi29** [comment]
@reubenvickers Thank you! It went through but now it says 

pi@raspberrypi:~ $ /home/pi/env/bin/python3 -u assistant.py
pubnub subscription completed
**Segmentation fault**
pi@raspberrypi:~ $ 

I will try to find another solution but thank you very much. I wouldn't have been able to figure that out lol

**Comment by reubenvickers** [comment]
I know this is closed now, but I believe if you cd into ~/MagicMirror/Modules/MMM-GoogleAssistant/pi
before running /home/pi/env/bin/python3 -u assistant.py, it should work.

**Comment by lordroi29** [comment]
<img width="681" alt="Screen Shot 2020-04-28 at 10 12 25 PM" src="https://user-images.githubusercontent.com/40746712/80555131-5f4d6580-899d-11ea-822c-cf7128fa2de8.png">

Nope, Still said the same thing @reubenvickers
