### ISSUE TITLE
Where to download assistant.py?

### ISSUE THREAD

**Issue by write2warriors** [gauravsacc/MMM-GoogleAssistant#67]
I am able to run the sample code from Google.  The push button works.

I am stuck with the step "Download the 'pi/assistant.py' script on your raspberry pi and launch it via terminal"

Where do I download it?

**Comment by varadwattamwar** [comment]
@write2warriors  I changed the subscribe key and public key in assistant.py also I entered magic-mirror-device-id but when I run assistant.py I receive msgs: pubnub subscription completed and hello from python!! but there is no response from google assistant , google assistant does not work. And my sample code also works fine. PLease help me out. Thanks in advance.
