### ISSUE TITLE
Assistant.py doesn't start

### ISSUE THREAD

**Issue by Bendumo** [gauravsacc/MMM-GoogleAssistant#7]
Hi,

I followed every steps and the "Google démo" work well but i can't find a way tout start the python script. I tried with "sudo python assistant.py" in the folder "mmm-googleassistant/pi" or in the home folder but none of them seem to work.

Have you got an Idea ?

Or can you describe the steps after the Google demo please. 

Thanks. 

Benjamin.

**Comment by gauravsacc** [comment]
do you see any error?

**Comment by Bendumo** [comment]
Hey,

When I try to do it in the /home/pi folder, there is this error : `"pi@MagicMirror:~ $ sudo python /home/pi/env/bin/python3 -u assistant.py
  File "/home/pi/env/bin/python3", line 1
SyntaxError: Non-ASCII character '\xc9' in file /home/pi/env/bin/python3 on line                                                                                                                                                              2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for detai                                                                                                                                                             ls"`

and when i just try `pi/assistant.py` in the home folder there is this error : `Traceback (most recent call last):
  File "assistant.py", line 24, in <module>
    import google.oauth2.credentials
ImportError: No module named google.oauth2.credentials
`
thanks.

**Comment by Bendumo** [comment]
Ok my bad ... I switch the publish and the subscribe key ... Sorry.

Now i can see `Hello from python` and everything work well. 

Thanks !

**Comment by Parthcool1** [comment]
@Bendumo what did you do to fix the no module named google.oauth2.credntials issue?

I am almost done with my mirror but I need help fixing this issue!
