### ISSUE TITLE
google-assistant-demo or assistant.py error

### ISSUE THREAD

**Issue by xzj739** [gauravsacc/MMM-GoogleAssistant#8]
when run google-assistant-demo following Installation of MMM-GoogleAssistant ,there is error below:
`(env) pi@raspberrypi:~ $ google-assistant-demo
ON_MUTED_CHANGED:
  {'is_muted': False}
ON_START_FINISHED
E0825 21:24:43.237547759    2322 handshake.c:128]            Security handshake failed: {"created":"@1503667483.237322448","description":"Handshake read failed","file":"../../third_party/grpc/src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1503667483.237302760","description":"FD shutdown","file":"../../third_party/grpc/src/core/lib/iomgr/ev_epoll_linux.c","file_line":1045}]}
E0825 21:24:44.239300845    2322 handshake.c:128]            Security handshake failed: {"created":"@1503667484.239134596","description":"Handshake read failed","file":"../../third_party/grpc/src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1503667484.239070534","description":"FD shutdown","file":"../../third_party/grpc/src/core/lib/iomgr/ev_epoll_linux.c","file_line":1045}]}
E0825 21:24:45.240707585    2322 handshake.c:128]            Security handshake failed: {"created":"@1503667485.240545242","description":"Handshake read failed","file":"../../third_party/grpc/src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1503667485.240474722","description":"FD shutdown","file":"../../third_party/grpc/src/core/lib/iomgr/ev_epoll_linux.c","file_line":1045}]}
E0825 21:24:46.242117767    2322 handshake.c:128]            Security handshake failed: {"created":"@1503667486.241883185","description":"Handshake read failed","file":"../../third_party/grpc/src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1503667486.241856779","description":"FD shutdown","file":"../../third_party/grpc/src/core/lib/iomgr/ev_epoll_linux.c","file_line":1045}]}
^Z
[6]+  已停止               google-assistant-demo
(env) pi@raspberrypi:~ $ python /home/pi/MagicMirror/modules/MMM-GoogleAssistant/pi/assistant.py
pubnub subscription completed
hello from python!!
E0825 21:26:38.974578276    2356 handshake.c:128]            Security handshake failed: {"created":"@1503667598.974480985","description":"Handshake read failed","file":"../../third_party/grpc/src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1503667598.974466662","description":"FD shutdown","file":"../../third_party/grpc/src/core/lib/iomgr/ev_epoll_linux.c","file_line":1045}]}
E0825 21:26:39.976059721    2356 handshake.c:128]            Security handshake failed: {"created":"@1503667599.975902534","description":"Handshake read failed","file":"../../third_party/grpc/src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1503667599.975882014","description":"FD shutdown","file":"../../third_party/grpc/src/core/lib/iomgr/ev_epoll_linux.c","file_line":1045}]}
E0825 21:26:40.978052364    2356 handshake.c:128]            Security handshake failed: {"created":"@1503667600.977887677","description":"Handshake read failed","file":"../../third_party/grpc/src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1503667600.977866792","description":"FD shutdown","file":"../../third_party/grpc/src/core/lib/iomgr/ev_epoll_linux.c","file_line":1045}]}
E0825 21:26:41.979422931    2356 handshake.c:128]            Security handshake failed: {"created":"@1503667601.979244859","description":"Handshake read failed","file":"../../third_party/grpc/src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1503667601.979218089","description":"FD shutdown","file":"../../third_party/grpc/src/core/lib/iomgr/ev_epoll_linux.c","file_line":1045}]}
E0825 21:26:48.174645386    2357 handshake.c:128]            Security handshake failed: {"created":"@1503667608.174485074","description":"Handshake read failed","file":"../../third_party/grpc/src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1503667608.174428564","description":"FD shutdown","file":"../../third_party/grpc/src/core/lib/iomgr/ev_epoll_linux.c","file_line":1045}]}
E0825 21:26:49.177164774    2357 handshake.c:128]            Security handshake failed: {"created":"@1503667609.177003005","description":"Handshake read failed","file":"../../third_party/grpc/src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1503667609.176978213","description":"FD shutdown","file":"../../third_party/grpc/src/core/lib/iomgr/ev_epoll_linux.c","file_line":1045}]}
E0825 21:26:50.178718444    2357 handshake.c:128]            Security handshake failed: {"created":"@1503667610.178565529","description":"Handshake read failed","file":"../../third_party/grpc/src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1503667610.178545216","description":"FD shutdown","file":"../../third_party/grpc/src/core/lib/iomgr/ev_epoll_linux.c","file_line":1045}]}
E0825 21:26:51.179974620    2357 handshake.c:128]            Security handshake failed: {"created":"@1503667611.179820611","description":"Handshake read failed","file":"../../third_party/grpc/src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1503667611.179802902","description":"FD shutdown","file":"../../third_party/grpc/src/core/lib/iomgr/ev_epoll_linux.c","file_line":1045}]}
`
anyone's help could be appreciated!

**Comment by gauravsacc** [comment]
Do you still have this issue or resolved?
