### ISSUE TITLE
No module named 'pubnub

### ISSUE THREAD

**Issue by dend3** [gauravsacc/MMM-GoogleAssistant#9]
Traceback (most recent call last):
  File "assistant.py", line 30, in <module>
    from pubnub.callbacks import SubscribeCallback
ImportError: No module named 'pubnub

**Comment by gauravsacc** [comment]
@dend3 please take a look at all closed issues. Already solved and most likely a configuration issue on your end.

**Comment by dend3** [comment]
Thank you, all working now,..

**Comment by mnail79** [comment]
Hi. I have the same problem. How do you resolve it. All closed issues couldnt help to me.
